work around some compiler issues with UxCom virtual destructor
- inline virtual destructor was causing issues in Fedora Rawhide gcc version 10.0.1:

/usr/bin/ld: /tmp/smithd.gMpQEQ.ltrans0.ltrans.o: in function `main':
/smithproxy/socle/tcpcom.hpp:41: undefined reference to `VTT for UxCom'
/usr/bin/ld: /tmp/smithd.gMpQEQ.ltrans0.ltrans.o:/smithproxy/socle/tcpcom.hpp:41: undefined reference to `VTT for UxCom'
/usr/bin/ld: /tmp/smithd.gMpQEQ.ltrans0.ltrans.o: in function `main':
/smithproxy/socle/uxcom.hpp:42: undefined reference to `vtable for UxCom'
/usr/bin/ld: /tmp/smithd.gMpQEQ.ltrans0.ltrans.o:/smithproxy/socle/uxcom.hpp:42: undefined reference to `vtable for UxCom'
/usr/bin/ld: /tmp/smithd.gMpQEQ.ltrans0.ltrans.o: in function `main':
/smithproxy/socle/tcpcom.hpp:45: undefined reference to `VTT for UxCom'
/usr/bin/ld: /tmp/smithd.gMpQEQ.ltrans0.ltrans.o:/smithproxy/socle/tcpcom.hpp:45: undefined reference to `VTT for UxCom'
collect2: error: ld returned 1 exit status

Turned out it works when making it off-line, putting definition in uxcom.cpp
Interesting is to note ubuntu 20.04 gcc 10.0.1 worked just fine without this workaround.